In [1]:
#每个文件夹下的readme文件为测试文件
from builder import ACTIVATIONS
import torch

cfg=dict(type='Sigmoid')
#会使用默认的build_func函数
sigmoid=ACTIVATIONS.build(cfg)
out=sigmoid(torch.randn(1))
print(out)

/root/anaconda3/envs/mmyolo/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


call Sigmoid.forward
tensor([-2.0184])


In [2]:
from builder import ACTIVATIONS
#调用父节点
cfg=dict(type='mmengine.LogSoftmax')
sigmoid=ACTIVATIONS.build(cfg)
out=sigmoid(torch.randn(1))
print(out)

call mmengine LogSoftmax.forward
tensor([0.2913])


In [3]:
cfg=dict(type='LogSoftmax')
#调用节点
sigmoid=ACTIVATIONS.build(cfg)
out=sigmoid(torch.randn(1))
print(out)

call register LogSoftmax.forward
tensor([2.0050])


In [5]:
#调用兄弟节点
cfg=dict(type='LogSoftmax',_scope_='config')
sigmoid=ACTIVATIONS.build(cfg)
out=sigmoid(torch.randn(1))
print(out)

08/18 08:41:11 - mmengine - WARNING - Failed to import `config.registry` make sure the registry.py exists in `config` package.
call config LogSoftmax.forward
tensor([-1.8385])
